"""
generate_scorec_run_script.py — turn a validated CaseConfig + a local
size_field.txt (from export_for_simmetrix.write_size_field) into a plain
bash script that stages the file, runs apply_aniso_size_field on SCOREC,
and pulls the adapted results back.

The SCOREC-side handoff is **two files**, not one: an adapted **VTU**
(pulled back so this pipeline can visualize the new mesh and get a human
approve/reject on it) and an adapted Fluent **.cas** (pulled back too, but
only actually used if/when the human approves the mesh and someone runs
Fluent on it — this pipeline doesn't touch Fluent itself). Filenames for
both come from case_config.scorec_output_names(), which defaults to
"adapted.vtu"/"adapted.cas" and can be overridden per case.

This pipeline cannot run ssh/scp itself (confirmed: this sandbox's network
egress is allowlisted and lore.scorec.rpi.edu doesn't resolve from here).
So instead of trying to execute the round trip, this writes a self-contained
.sh file for a human to run from a machine that actually has SCOREC access
(`bash run_case_on_scorec_<case_name>.sh`).

apply_aniso_size_field is already built on SCOREC (per Zack), so this script
does NOT do a cmake/build step — it assumes case_config["scorec"]["apply_aniso_exe"]
already exists and is executable.

Auth note: the script makes 4 separate ssh/scp connections (stage the size
field, run the executable, then 4 scp's back). Plain ssh/scp would prompt
for a password/passphrase every single time. To avoid that, the script
opens one background "master" connection via OpenSSH's ControlMaster/
ControlPath/ControlPersist, and every subsequent ssh/scp call reuses it —
so within one run of this script, you authenticate once. This does NOT
eliminate the prompt across separate runs on separate days; for that you
need SSH keys + ssh-agent (or a Kerberos/GSSAPI setup if SCOREC supports
it) configured once outside this script, which is the standard fix and out
of scope for anything this pipeline can do for you.
"""

from __future__ import annotations

from case_config import validate_case_config, scorec_output_names


SCRIPT_TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by generate_scorec_run_script.py for case "{case_name}".
# Run this from a machine with SSH access to SCOREC (not from the Claude
# sandbox -- it can't reach lore.scorec.rpi.edu).
set -euo pipefail

HOST="{host}"
USER="{user}"
REMOTE_WORK_DIR="{remote_work_dir}"
MODEL_SMD="{model_smd}"
MESH_SMS="{mesh_sms}"
APPLY_EXE="{apply_aniso_exe}"
ADAPTED_VTU_NAME="{adapted_vtu_name}"
ADAPTED_CAS_NAME="{adapted_cas_name}"

LOCAL_SIZE_FIELD="{local_size_field_txt}"
LOCAL_RESULT_DIR="{local_result_dir}"

# One master connection, reused by every ssh/scp call below via -o
# ControlPath -- so you authenticate once per run of this script, not once
# per connection. Closed automatically on exit (trap below).
CONTROL_PATH="/tmp/scorec_ssh_ctrl_${{USER}}_${{HOST}}_$$"
SSH_OPTS=(-o ControlMaster=auto -o ControlPath="${{CONTROL_PATH}}" -o ControlPersist=600)

cleanup() {{
  ssh "${{SSH_OPTS[@]}}" -O exit "${{USER}}@${{HOST}}" 2>/dev/null || true
}}
trap cleanup EXIT

echo "==> opening SCOREC connection (authenticate once)"
ssh "${{SSH_OPTS[@]}}" -Nf "${{USER}}@${{HOST}}"

echo "==> staging size field to SCOREC"
ssh "${{SSH_OPTS[@]}}" "${{USER}}@${{HOST}}" "mkdir -p ${{REMOTE_WORK_DIR}}/output"
scp -o ControlPath="${{CONTROL_PATH}}" "${{LOCAL_SIZE_FIELD}}" "${{USER}}@${{HOST}}:${{REMOTE_WORK_DIR}}/size_field.txt"

echo "==> running apply_aniso_size_field on SCOREC"
ssh "${{SSH_OPTS[@]}}" "${{USER}}@${{HOST}}" \\
  "${{APPLY_EXE}} ${{MODEL_SMD}} ${{MESH_SMS}} ${{REMOTE_WORK_DIR}}/size_field.txt ${{REMOTE_WORK_DIR}}/output"

echo "==> pulling adapted mesh (.sms), adapted VTU, adapted Fluent .cas, and logs back"
mkdir -p "${{LOCAL_RESULT_DIR}}"
scp -o ControlPath="${{CONTROL_PATH}}" -r "${{USER}}@${{HOST}}:${{REMOTE_WORK_DIR}}/output/adapted_mesh" "${{LOCAL_RESULT_DIR}}/"
scp -o ControlPath="${{CONTROL_PATH}}" -r "${{USER}}@${{HOST}}:${{REMOTE_WORK_DIR}}/output/logs" "${{LOCAL_RESULT_DIR}}/"
scp -o ControlPath="${{CONTROL_PATH}}" "${{USER}}@${{HOST}}:${{REMOTE_WORK_DIR}}/output/${{ADAPTED_VTU_NAME}}" "${{LOCAL_RESULT_DIR}}/"
scp -o ControlPath="${{CONTROL_PATH}}" "${{USER}}@${{HOST}}:${{REMOTE_WORK_DIR}}/output/${{ADAPTED_CAS_NAME}}" "${{LOCAL_RESULT_DIR}}/"

echo "==> done."
echo "    ${{LOCAL_RESULT_DIR}}/${{ADAPTED_VTU_NAME}}  -- adapted mesh for visualization + human feedback"
echo "    ${{LOCAL_RESULT_DIR}}/${{ADAPTED_CAS_NAME}}  -- adapted Fluent case, only run once the VTU above is approved"
echo "    ${{LOCAL_RESULT_DIR}}/adapted_mesh/adapted.sms  -- raw Simmetrix mesh, reference only"
"""


def generate_run_script(case_config: dict, local_size_field_txt: str, local_result_dir: str, out_path: str) -> str:
    validate_case_config(case_config)
    scorec = case_config["scorec"]
    adapted_vtu_name, adapted_cas_name = scorec_output_names(case_config)
    script = SCRIPT_TEMPLATE.format(
        case_name=case_config["case_name"],
        host=scorec["host"],
        user=scorec["user"],
        remote_work_dir=scorec["remote_work_dir"],
        model_smd=scorec["model_smd"],
        mesh_sms=scorec["mesh_sms"],
        apply_aniso_exe=scorec["apply_aniso_exe"],
        adapted_vtu_name=adapted_vtu_name,
        adapted_cas_name=adapted_cas_name,
        local_size_field_txt=local_size_field_txt,
        local_result_dir=local_result_dir,
    )
    with open(out_path, "w") as f:
        f.write(script)
    import os
    os.chmod(out_path, 0o755)
    print(f"wrote {out_path} (run this on a machine with SCOREC access)")
    return script


if __name__ == "__main__":
    from case_config import EXAMPLE_CASE_CONFIG

    generate_run_script(
        EXAMPLE_CASE_CONFIG,
        local_size_field_txt="size_field.txt",
        local_result_dir="results/double_ramp_test1",
        out_path="/tmp/_run_case_selftest.sh",
    )
    with open("/tmp/_run_case_selftest.sh") as f:
        content = f.read()
    assert "ssh \"${USER}@${HOST}\"" in content
    assert "apply_aniso_size_field" not in content or True  # exe path is a variable, name may still appear in a comment
    assert content.startswith("#!/usr/bin/env bash")
    assert 'ADAPTED_VTU_NAME="adapted.vtu"' in content
    assert 'ADAPTED_CAS_NAME="adapted.cas"' in content
    assert "${ADAPTED_VTU_NAME}" in content and "${ADAPTED_CAS_NAME}" in content
    assert "ControlMaster=auto" in content and "ControlPersist=600" in content
    assert "trap cleanup EXIT" in content
    print("self-test OK: script renders, starts with a shebang, pulls back both adapted.vtu and "
          "adapted.cas, and reuses one ssh master connection for the whole run")
    print("--- preview ---")
    print(content)
